### ISSUE TITLE
IMYWebLoader在iOS15上会发生崩溃

### ISSUE THREAD

**Issue by duangchen** [li6185377/IMYWebLoader#21]
集成之后，在iOS15上会崩溃在wkloader_hookWKLoader:request这个方法里面

**Comment by cnzlh** [comment]
![image](https://user-images.githubusercontent.com/5771860/228712049-ce552bb3-a54c-403c-ab2d-7cdbc47ad57e.png)

**Comment by cnzlh** [comment]
![image](https://user-images.githubusercontent.com/5771860/228712149-8435e640-73c1-48f1-a6d3-b6aa8b3562e7.png)

**Comment by li6185377** [comment]
NSURLConnection 已经废弃很久了， 该库其实我也一直没维护了，推荐使用 ：KKJSBridge
